### ISSUE TITLE
What test can I use to test for significant differences between treatments using gam

### ISSUE THREAD

**Issue by carloshenriquezc** [m-clark/generalized-additive-models#11]
Hi, everyone.
Thanks for this excelent tutorial for using gam. 
I perfomed gam to my dataset testing the effect of phosphate addition in the growth of plants from three different locations.
I am wonder how to test for significant differences when comparing the three different locations.

Thanks in advance!

**Comment by m-clark** [comment]
If you have a `by` statement, e.g. `s(phos, by = loc)` then you will get smooths for each location.  You can also use the factor smooth approach, which basically treats it like a random slope for each location as in a mixed model.  That is, you don't need separate models, just one that allows the effect to vary by location.  Otherwise your models aren't really comparable as they are fit to different data.  And while the approach just mentioned will give you statistical results, you'd probably do better just comparing AIC with the model with and without the `by` approach.

Also, I don't mind answering questions if I can, but if you would, please reserve github issues for something specific to the doc (e.g. typos, code problem, etc.).  I'm going to go ahead and close this as it's not specific to the document.

Glad you're finding the doc useful!
